spring:
  application:
    name: coresystem-poc
  mvc:
    servlet:
      path: /api
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:dcbapp;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: update
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

server:
  address: 0.0.0.0
  port: 8080

#Environment variables
timeslot:
  length: ${ENV_TIMESLOT_LENGTH:15}
ping:
  interval: ${ENV_TIMESLOT_LENGTH:6}